#!/usr/bin/env python3
"""
Sync i18n locales from desktop_client to android_client.
Generates Kotlin singleton maps in com.gpdb.android.util.locales.*
"""

import os
import re
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DESKTOP_LOCALES_DIR = os.path.join(BASE_DIR, "desktop_client", "src", "i18n", "locales")
ANDROID_LOCALES_DIR = os.path.join(BASE_DIR, "android_client", "app", "src", "main", "java", "com", "gpdb", "android", "util", "locales")

LOCALE_MAP = {
    "zh-CN": ("LocaleZhCn", "ZH_CN"),
    "zh-TW": ("LocaleZhTw", "ZH_TW"),
    "en": ("LocaleEn", "EN"),
    "ja": ("LocaleJa", "JA"),
    "it": ("LocaleIt", "IT"),
    "es": ("LocaleEs", "ES"),
    "de": ("LocaleDe", "DE")
}

def parse_ts_locale(filepath):
    """
    Parses a TypeScript locale export object.
    Lines format: 'key': 'value',
    """
    entries = {}
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Pattern matches 'key': 'value'
    # Handling escaped single quotes (\') inside values
    pattern = re.compile(r"^\s*'([^']+)'\s*:\s*'((?:[^'\\]|\\.)*)',?", re.MULTILINE)
    for match in pattern.finditer(content):
        key = match.group(1)
        raw_val = match.group(2)
        # unescape \' to '
        val = raw_val.replace(r"\'", "'")
        entries[key] = val

    return entries

def escape_kotlin_string(val):
    # Escape \ and " and $ for Kotlin strings
    s = val.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    s = s.replace('$', '\\$')
    return s

def generate_kotlin_file(class_name, enum_name, entries):
    lines = [
        "package com.gpdb.android.util.locales",
        "",
        "// Auto-generated by tools/sync_desktop_i18n_to_android.py",
        "// Do NOT edit manually.",
        f"object {class_name} {{",
        "    val translations: Map<String, String> = mapOf("
    ]

    sorted_keys = sorted(entries.keys())
    for i, k in enumerate(sorted_keys):
        v = entries[k]
        escaped_v = escape_kotlin_string(v)
        comma = "," if i < len(sorted_keys) - 1 else ""
        lines.append(f'        "{k}" to "{escaped_v}"{comma}')

    lines.append("    )")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)

def main():
    if not os.path.isdir(DESKTOP_LOCALES_DIR):
        print(f"Error: Desktop locales directory not found: {DESKTOP_LOCALES_DIR}")
        sys.exit(1)

    os.makedirs(ANDROID_LOCALES_DIR, exist_ok=True)

    all_data = {}
    for code, (class_name, enum_name) in LOCALE_MAP.items():
        ts_path = os.path.join(DESKTOP_LOCALES_DIR, f"{code}.ts")
        if not os.path.isfile(ts_path):
            print(f"Error: Missing locale file {ts_path}")
            sys.exit(1)
        entries = parse_ts_locale(ts_path)
        all_data[code] = entries
        print(f"Parsed {code}.ts: {len(entries)} keys")

    # Check key parity
    base_keys = set(all_data["zh-CN"].keys())
    for code, entries in all_data.items():
        missing = base_keys - set(entries.keys())
        extra = set(entries.keys()) - base_keys
        if missing or extra:
            print(f"Warning: {code} has differences with zh-CN! Missing: {len(missing)}, Extra: {len(extra)}")

    # Write Kotlin files
    for code, (class_name, enum_name) in LOCALE_MAP.items():
        kt_content = generate_kotlin_file(class_name, enum_name, all_data[code])
        kt_path = os.path.join(ANDROID_LOCALES_DIR, f"{class_name}.kt")
        with open(kt_path, "w", encoding="utf-8") as f:
            f.write(kt_content)
        print(f"Generated {kt_path} ({len(all_data[code])} keys)")

    print("Successfully synchronized all i18n locales to Android!")

if __name__ == "__main__":
    main()
